apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix
  labels:
    app: phoenix
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phoenix
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: phoenix
    spec:
      containers:
        - image: hanisharora/phoenix
          imagePullPolicy: IfNotPresent
          name: phoenix
          ports:
            - containerPort: 80
