version: 2.1
jobs:
  lint:
    docker:
      - image: python:3.7.3-stretch

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: INSTALL DEPENDENCIES
          command: |
            python3 -m venv phoenix
            . phoenix/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.8.0/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
      - run:
          name: RUN LINT
          command: |
            . phoenix/bin/activate
            make lint

workflow:
  build-push-deploy:
    jobs:
      - lint
